import jsPDF from "jspdf";
import "jspdf-autotable";

export const generateInvoice = (saleData) => {
  const {
    saleId,
    items,
    subtotal,
    discount = 0,
    tax,
    total,
    paymentMethod,
    customerName = "Guest",
  } = saleData;

  const doc = new jsPDF();

  // ===== Header =====
  doc.setFontSize(20);
  doc.setTextColor(40, 116, 240);
  doc.text("StockFlow", 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Inventory & Billing System", 14, 26);

  doc.setFontSize(12);
  doc.text(`Sale ID: ${saleId}`, 150, 20);
  doc.text(`Date: ${new Date().toLocaleString()}`, 150, 26);
  doc.text(`Customer: ${customerName}`, 150, 32);

  // ===== Table =====
  const tableData = items.map((item, index) => [
    index + 1,
    item.name,
    item.qty,
    `$${item.price.toFixed(2)}`,
    `$${(item.price * item.qty).toFixed(2)}`,
  ]);

  doc.autoTable({
    startY: 40,
    head: [["#", "Item", "Qty", "Price", "Subtotal"]],
    body: tableData,
    theme: "grid",
    headStyles: { fillColor: [67, 56, 202] }, // violet
    styles: { fontSize: 10 },
  });

  // ===== Totals =====
  const y = doc.lastAutoTable.finalY + 10;

  doc.setFontSize(12);
  doc.text("Summary", 14, y);
  doc.setFontSize(10);

  const summary = [
    ["Subtotal", `$${subtotal.toFixed(2)}`],
    ["Discount", `-${discount}%`],
    ["Tax (18%)", `$${tax.toFixed(2)}`],
    ["Total", `$${total.toFixed(2)}`],
    ["Payment Method", paymentMethod.toUpperCase()],
  ];

  summary.forEach(([label, value], i) => {
    const posY = y + 6 + i * 6;
    doc.text(label, 14, posY);
    doc.text(value, 180, posY, { align: "right" });
  });

  // ===== Footer =====
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    "Thank you for shopping with us!",
    14,
    doc.internal.pageSize.height - 20
  );
  doc.text(
    "Generated by StockFlow POS System",
    14,
    doc.internal.pageSize.height - 15
  );

  // ===== Save PDF =====
  doc.save(`${saleId || "invoice"}.pdf`);
};
